/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SchadenmeldungRouteImport } from './routes/schadenmeldung'
import { Route as ObjekteRouteImport } from './routes/objekte'
import { Route as NotfallRouteImport } from './routes/notfall'
import { Route as MieterDokumenteRouteImport } from './routes/mieter-dokumente'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as EigentuemerRouteImport } from './routes/eigentuemer'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SchadenmeldungRoute = SchadenmeldungRouteImport.update({
  id: '/schadenmeldung',
  path: '/schadenmeldung',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjekteRoute = ObjekteRouteImport.update({
  id: '/objekte',
  path: '/objekte',
  getParentRoute: () => rootRouteImport,
} as any)
const NotfallRoute = NotfallRouteImport.update({
  id: '/notfall',
  path: '/notfall',
  getParentRoute: () => rootRouteImport,
} as any)
const MieterDokumenteRoute = MieterDokumenteRouteImport.update({
  id: '/mieter-dokumente',
  path: '/mieter-dokumente',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const EigentuemerRoute = EigentuemerRouteImport.update({
  id: '/eigentuemer',
  path: '/eigentuemer',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/eigentuemer': typeof EigentuemerRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mieter-dokumente': typeof MieterDokumenteRoute
  '/notfall': typeof NotfallRoute
  '/objekte': typeof ObjekteRoute
  '/schadenmeldung': typeof SchadenmeldungRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/eigentuemer': typeof EigentuemerRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mieter-dokumente': typeof MieterDokumenteRoute
  '/notfall': typeof NotfallRoute
  '/objekte': typeof ObjekteRoute
  '/schadenmeldung': typeof SchadenmeldungRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/eigentuemer': typeof EigentuemerRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mieter-dokumente': typeof MieterDokumenteRoute
  '/notfall': typeof NotfallRoute
  '/objekte': typeof ObjekteRoute
  '/schadenmeldung': typeof SchadenmeldungRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/eigentuemer'
    | '/impressum'
    | '/kontakt'
    | '/mieter-dokumente'
    | '/notfall'
    | '/objekte'
    | '/schadenmeldung'
    | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/eigentuemer'
    | '/impressum'
    | '/kontakt'
    | '/mieter-dokumente'
    | '/notfall'
    | '/objekte'
    | '/schadenmeldung'
    | '/ueber-uns'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/eigentuemer'
    | '/impressum'
    | '/kontakt'
    | '/mieter-dokumente'
    | '/notfall'
    | '/objekte'
    | '/schadenmeldung'
    | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EigentuemerRoute: typeof EigentuemerRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MieterDokumenteRoute: typeof MieterDokumenteRoute
  NotfallRoute: typeof NotfallRoute
  ObjekteRoute: typeof ObjekteRoute
  SchadenmeldungRoute: typeof SchadenmeldungRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schadenmeldung': {
      id: '/schadenmeldung'
      path: '/schadenmeldung'
      fullPath: '/schadenmeldung'
      preLoaderRoute: typeof SchadenmeldungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekte': {
      id: '/objekte'
      path: '/objekte'
      fullPath: '/objekte'
      preLoaderRoute: typeof ObjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfall': {
      id: '/notfall'
      path: '/notfall'
      fullPath: '/notfall'
      preLoaderRoute: typeof NotfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mieter-dokumente': {
      id: '/mieter-dokumente'
      path: '/mieter-dokumente'
      fullPath: '/mieter-dokumente'
      preLoaderRoute: typeof MieterDokumenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eigentuemer': {
      id: '/eigentuemer'
      path: '/eigentuemer'
      fullPath: '/eigentuemer'
      preLoaderRoute: typeof EigentuemerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  EigentuemerRoute: EigentuemerRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MieterDokumenteRoute: MieterDokumenteRoute,
  NotfallRoute: NotfallRoute,
  ObjekteRoute: ObjekteRoute,
  SchadenmeldungRoute: SchadenmeldungRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
